[secrets]
PAT="b50e6cd36a9a486283d9161c31a498f8"
Llama_USER_ID = "meta"
Llama_APP_ID = "Llama-2"
Llama_MODEL_ID = "llama2-70b-chat"
MC_USER_ID = 'engenair'
MC_APP_ID = 'pharmogle'
MC_MODEL_ID = 'pharmogle-dev-v1'
MC_MODEL_VERSION_ID = 'b652f86cc8f346c3bce068a7459f8c91'